theme: jekyll-theme-cayman
title: *Platynereis dumerilii*
description: Welcome to the *Platynereis* website. The website includes information about *Platynereis*, existing resources, *Platynereis* labs and a short overview of further annelid research. 
